name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Publish
      run: dotnet publish -c Release --no-build -o ${{env.DOTNET_ROOT}}/live

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'integracja'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5568a99b102a49df9913bbe31b8cb0d2 }}
        package: ${{env.DOTNET_ROOT}}/live 
